const TEMPERATURES_REQUESTED = "TEMPERATURES_REQUESTED";
const TEMPERATURES_REQUEST_SUCCEEDED = "TEMPERATURES_REQUEST_SUCCEEDED";
const TEMPERATURES_REQUEST_FAILED = "TEMPERATURES_REQUEST_FAILED";

export {
  TEMPERATURES_REQUESTED,
  TEMPERATURES_REQUEST_SUCCEEDED,
  TEMPERATURES_REQUEST_FAILED
};
