const COUCHDB_AUTHENTICATION_REQUESTED = "COUCHDB_AUTHENTICATION_REQUESTED";
const COUCHDB_AUTHENTICATION_SUCCEEDED = "COUCHDB_AUTHENTICATION_SUCCEEDED";
const COUCHDB_AUTHENTICATION_FAILED = "COUCHDB_AUTHENTICATION_FAILED";

export {
  COUCHDB_AUTHENTICATION_REQUESTED,
  COUCHDB_AUTHENTICATION_SUCCEEDED,
  COUCHDB_AUTHENTICATION_FAILED
};
