const UPDATE_PAGE = "UPDATE_PAGE";
const UPDATE_OFFLINE = "UPDATE_OFFLINE";
const UPDATE_DRAWER_STATE = "UPDATE_DRAWER_STATE";
const OPEN_SNACKBAR = "OPEN_SNACKBAR";
const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export {
  UPDATE_PAGE,
  UPDATE_OFFLINE,
  UPDATE_DRAWER_STATE,
  OPEN_SNACKBAR,
  CLOSE_SNACKBAR
};
